name: release
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push latest
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/riposo/cmd:latest
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      - name: Build and push version
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/riposo/cmd:${{ steps.get_version.outputs.version-without-v }}
            ghcr.io/riposo/cmd:${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
